package com.ctvit.entity;

import java.util.Date;

public class UserInf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.USER_ID
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.USER_NAME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.USER_NICKNAME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String userNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.USER_PASSWORD
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.SEX
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.BIRTH_DATE
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private Date birthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.EMAIL
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.WORK_PHONE
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String workPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.MOBILE_PHONE
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.POSITION
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.LOAGIN_STATUS
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String loaginStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.LAST_LOGIN_TIME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.LAST_EXIT_TIME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private Date lastExitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.DESCRIPTION
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.DEPARTMENT_ID
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.STATUS_FLAG
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private String statusFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.CREATE_TIME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.DELETE_TIME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_user_inf.NEED_CHECK_FLAG
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    private Short needCheckFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.USER_ID
     *
     * @return the value of tab_user_inf.USER_ID
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.USER_ID
     *
     * @param userId the value for tab_user_inf.USER_ID
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.USER_NAME
     *
     * @return the value of tab_user_inf.USER_NAME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.USER_NAME
     *
     * @param userName the value for tab_user_inf.USER_NAME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.USER_NICKNAME
     *
     * @return the value of tab_user_inf.USER_NICKNAME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.USER_NICKNAME
     *
     * @param userNickname the value for tab_user_inf.USER_NICKNAME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.LOGIN_NAME
     *
     * @return the value of tab_user_inf.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.LOGIN_NAME
     *
     * @param loginName the value for tab_user_inf.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.USER_PASSWORD
     *
     * @return the value of tab_user_inf.USER_PASSWORD
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.USER_PASSWORD
     *
     * @param userPassword the value for tab_user_inf.USER_PASSWORD
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.SEX
     *
     * @return the value of tab_user_inf.SEX
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.SEX
     *
     * @param sex the value for tab_user_inf.SEX
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.BIRTH_DATE
     *
     * @return the value of tab_user_inf.BIRTH_DATE
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.BIRTH_DATE
     *
     * @param birthDate the value for tab_user_inf.BIRTH_DATE
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.EMAIL
     *
     * @return the value of tab_user_inf.EMAIL
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.EMAIL
     *
     * @param email the value for tab_user_inf.EMAIL
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.WORK_PHONE
     *
     * @return the value of tab_user_inf.WORK_PHONE
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getWorkPhone() {
        return workPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.WORK_PHONE
     *
     * @param workPhone the value for tab_user_inf.WORK_PHONE
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setWorkPhone(String workPhone) {
        this.workPhone = workPhone == null ? null : workPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.MOBILE_PHONE
     *
     * @return the value of tab_user_inf.MOBILE_PHONE
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.MOBILE_PHONE
     *
     * @param mobilePhone the value for tab_user_inf.MOBILE_PHONE
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.POSITION
     *
     * @return the value of tab_user_inf.POSITION
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.POSITION
     *
     * @param position the value for tab_user_inf.POSITION
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.LOAGIN_STATUS
     *
     * @return the value of tab_user_inf.LOAGIN_STATUS
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getLoaginStatus() {
        return loaginStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.LOAGIN_STATUS
     *
     * @param loaginStatus the value for tab_user_inf.LOAGIN_STATUS
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setLoaginStatus(String loaginStatus) {
        this.loaginStatus = loaginStatus == null ? null : loaginStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.LAST_LOGIN_TIME
     *
     * @return the value of tab_user_inf.LAST_LOGIN_TIME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for tab_user_inf.LAST_LOGIN_TIME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.LAST_EXIT_TIME
     *
     * @return the value of tab_user_inf.LAST_EXIT_TIME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public Date getLastExitTime() {
        return lastExitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.LAST_EXIT_TIME
     *
     * @param lastExitTime the value for tab_user_inf.LAST_EXIT_TIME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setLastExitTime(Date lastExitTime) {
        this.lastExitTime = lastExitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.DESCRIPTION
     *
     * @return the value of tab_user_inf.DESCRIPTION
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.DESCRIPTION
     *
     * @param description the value for tab_user_inf.DESCRIPTION
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.DEPARTMENT_ID
     *
     * @return the value of tab_user_inf.DEPARTMENT_ID
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.DEPARTMENT_ID
     *
     * @param departmentId the value for tab_user_inf.DEPARTMENT_ID
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.STATUS_FLAG
     *
     * @return the value of tab_user_inf.STATUS_FLAG
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public String getStatusFlag() {
        return statusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.STATUS_FLAG
     *
     * @param statusFlag the value for tab_user_inf.STATUS_FLAG
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setStatusFlag(String statusFlag) {
        this.statusFlag = statusFlag == null ? null : statusFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.CREATE_TIME
     *
     * @return the value of tab_user_inf.CREATE_TIME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.CREATE_TIME
     *
     * @param createTime the value for tab_user_inf.CREATE_TIME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.DELETE_TIME
     *
     * @return the value of tab_user_inf.DELETE_TIME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.DELETE_TIME
     *
     * @param deleteTime the value for tab_user_inf.DELETE_TIME
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_user_inf.NEED_CHECK_FLAG
     *
     * @return the value of tab_user_inf.NEED_CHECK_FLAG
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public Short getNeedCheckFlag() {
        return needCheckFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_user_inf.NEED_CHECK_FLAG
     *
     * @param needCheckFlag the value for tab_user_inf.NEED_CHECK_FLAG
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    public void setNeedCheckFlag(Short needCheckFlag) {
        this.needCheckFlag = needCheckFlag;
    }
}