package com.ctvit.dao;

import com.ctvit.entity.UserInf;
import com.ctvit.entity.UserInfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_inf
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    int countByExample(UserInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_inf
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    int deleteByExample(UserInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_inf
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_inf
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    int insert(UserInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_inf
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    int insertSelective(UserInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_inf
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    List<UserInf> selectByExample(UserInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_inf
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    UserInf selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_inf
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserInf record, @Param("example") UserInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_inf
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    int updateByExample(@Param("record") UserInf record, @Param("example") UserInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_inf
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    int updateByPrimaryKeySelective(UserInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_inf
     *
     * @mbggenerated Tue Jun 26 11:41:27 CST 2018
     */
    int updateByPrimaryKey(UserInf record);
}